### ISSUE TITLE
convert video into gif

### ISSUE THREAD

**Issue by nqueuche** [jukefr/fyle#47]
It would be great to convert a video into a gif.
To optimize the size of the gif, we should define at least : 
- The scale 
- The FPS
- The quality

**Comment by jukefr** [comment]
you can :
1. fconvert video input.ext output.gif
2. fps is not available yet but I plan to add an futil
3. foptimize image gif output.gif

**Comment by jukefr** [comment]
Also see fcli to use these commands easier
